name: build

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout source
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v3
      with:
        hugo-version: '0.164.0'
        extended: true

    - name: Build
      run: hugo --gc --minify --cleanDestinationDir

    - name: Deploy
      env:
        TZ: Asia/Shanghai
        DEPLOY_REPO: guanqr/guanqr.github.io
        DEPLOY_BRANCH: master
        PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
      run: |
        cd ./public && git init
        git config user.name "guanqr"
        git config user.email "guanqirui@zju.edu.cn"
        git add .
        git commit -m "Automated Deployment @ $(date '+%Y-%m-%d %H:%M:%S') ${TZ}"
        git push --force --quiet "https://$PERSONAL_TOKEN@github.com/$DEPLOY_REPO" master:$DEPLOY_BRANCH